steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/data-hangout-442823-j3/kunal-100974945/image:${COMMIT_SHA}', '.']

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/data-hangout-442823-j3/kunal-100974945/image:${COMMIT_SHA}']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'kunal-sn-00001-jsl', '--image', 'us-central1-docker.pkg.dev/data-hangout-442823-j3/kunal-100974945/image:${COMMIT_SHA}', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
