version: "3.9"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kamal[YourStudentID]
      POSTGRES_DB: labonedb
    depends_on:
      db:
        condition: service_healthy
 
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kamal[YourStudentID]
      POSTGRES_DB: labonedb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
 
volumes:
  db-data:
